# Project
project: Jumpgate
lead: "Because Landreth just had to ruin it for everybody"
public_url: http://softlayer.github.io/jumpgate

# Versions
version: 0.0.1

# GitHub
repo: https://github.com/softlayer/jumpgate
fork: http://ghbtns.com/github-btn.html?user=softlayer&amp;repo=jumpgate&amp;type=fork&amp;count=true
star: http://ghbtns.com/github-btn.html?user=softlayer&amp;repo=jumpgate&amp;type=watch&amp;count=true
open_issues: http://github.com/softlayer/jumpgate/issues?milestone=1;state=open
closed_issues: http://github.com/softlayer/jumpgate/issues?milestone=1;state=closed
milestones: https://github.com/softlayer/jumpgate/issues/milestones?state=open

# Company
www: http://www.softlayer.com
license: https://github.com/softlayer/jumpgate/blob/master/LICENSE
sldn: http://sldn.softlayer.com
kb: http://knowledgelayer.softlayer.com
portal: http://manage.softlayer.com

# Social
github: http://github.com/softlayer
twitter: http://twitter.com/softlayerdevs

# Server
permalink: pretty
exclude: [".gitignore", "LICENSE", "README.md", "humans.txt", "TODO.md"]